-- Super-admin sales dashboard security.
-- The UI is not the security boundary: admin access is enforced in Postgres.
--
-- Esta migration foi esvaziada de propósito. A versão original:
--
--   1) chamava public.has_role('admin'::app_role, auth.uid()) — ordem de
--      argumentos invertida. A assinatura real é has_role(_user_id uuid,
--      _role app_role), então a função não existe nessa ordem e a migration
--      falhava ao aplicar.
--
--   2) concedia "for all" em public.orders, o que inclui DELETE: um admin
--      poderia apagar registros financeiros. Pedido pago é documento
--      contábil e não deve ser removível pela interface.
--
-- As policies equivalentes já foram criadas na migration de superadmin, com
-- a assinatura correta e escopo restrito:
--
--   orders       -> SELECT + UPDATE (sem DELETE), toda escrita auditada
--   order_items  -> SELECT
--   profiles     -> ALL
--
-- Além disso, o trigger protect_gateway_link mantém total_cents,
-- pagarme_order_id e pagarme_charge_id imutáveis após a cobrança existir,
-- preservando a conciliação com o extrato do gateway.
--
-- Nada a executar aqui.
SELECT 1;
